"""Remediation module

Generates PowerShell scripts to remove mis‑configured ACLs discovered by the pathfinder.
"""
from typing import List

def generate_ps_script(acl_issues: List[dict]) -> str:
    """Create a PowerShell script that removes the provided ACL issues.

    Each ``acl_issues`` entry is expected to contain the necessary information
    (e.g., target object, permission to remove, trustee). This stub returns a
    placeholder script; actual implementation will format real commands.
    """
    lines = ["# PowerShell remediation script generated by ViperACL", ""]
    for issue in acl_issues:
        # Example placeholder – real code would use issue fields
        lines.append(f"# Remove ACL: {issue.get('description', 'unknown')}")
        lines.append("# Remove‑ADPermission -Identity <Object> -User <User> -AccessRights <Rights>")
        lines.append("")
    return "\n".join(lines)
