# core/remediation/ps_templates.py

HEADER = """<#
.SYNOPSIS
    ViperACL Automated Remediation Script
.DESCRIPTION
    This script was automatically generated by ViperACL (Phase 4).
    It contains specific mitigation steps to break identified Active Directory attack paths.
#>
Import-Module ActiveDirectory
Set-Location AD:

$ErrorActionPreference = "Stop"
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host " Starting ViperACL Remediation Protocol" -ForegroundColor Cyan
Write-Host "=================================================`n" -ForegroundColor Cyan
"""

FOOTER = """
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host " Remediation Protocol Complete." -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Cyan
"""

# Template for Group Membership (Cost: 0)
REMOVE_GROUP_MEMBER = """
Write-Host "[*] Action: Remove '{source}' from group '{target}'"
try {{
    # Safely resolve Distinguished Names first to prevent null Identity errors
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'"
    $SourceObj = Get-ADObject -Filter "Name -eq '{source}' -or SamAccountName -eq '{source}'"
    
    if (-not $TargetObj) {{ throw "Could not resolve target group '{target}' in AD." }}
    if (-not $SourceObj) {{ throw "Could not resolve source user '{source}' in AD." }}

    # Check if the user is actually a member of the group first
    $CurrentMembers = Get-ADGroupMember -Identity $TargetObj.DistinguishedName
    $IsMember = $CurrentMembers | Where-Object {{ $_.DistinguishedName -eq $SourceObj.DistinguishedName }}

    if ($IsMember) {{
        Remove-ADGroupMember -Identity $TargetObj.DistinguishedName -Members $SourceObj.DistinguishedName -Confirm:$false
        Write-Host "  [+] SUCCESS: User removed from group." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: User is not currently a member of this group. No action needed." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# Template for standard and structural ACLs (Cost: 1, 2, 3)
REMOVE_GENERIC_ACL = """
Write-Host "[*] Action: Remove '{ad_right}' right for '{source}' on '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) {{ throw "Could not resolve target '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $RulesToRemove = $Acl.Access | Where-Object {{ $_.IdentityReference.Value -match "{source}" -and $_.ActiveDirectoryRights -match "{ad_right}" }}

    if ($RulesToRemove) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Removed ACE granting {ad_right}." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No matching ACE found. It may have already been removed." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# Template for Destructive actions: Strip ForceChangePassword (Cost: 5)
REMOVE_FORCE_CHANGE_PASSWORD = """
Write-Host "[*] Action: Remove 'ForceChangePassword' right for '{source}' on '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) {{ throw "Could not resolve target '{target}' in AD." }}

    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    # GUID for User-Force-Change-Password Extended Right
    $ResetPwGuid = "00299570-246d-11d0-a768-00aa006e0529" 
    
    $RulesToRemove = $Acl.Access | Where-Object {{ $_.IdentityReference.Value -match "{source}" -and $_.ObjectType -eq $ResetPwGuid }}

    if ($RulesToRemove) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Stripped ForceChangePassword privilege." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No ForceChangePassword ACE found. It may have already been removed." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# Template for Domain-level DCSync rights (Cost: 0)
REMOVE_DCSYNC = """
Write-Host "[*] Action: Remove DCSync (GetChanges/All) for '{source}' on Domain Root '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) {{ throw "Could not resolve Domain Root '{target}' in AD." }}

    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $SyncGuids = @("1131f6aa-9c07-11d1-f79f-00c04fc2dcd2", "1131f6ad-9c07-11d1-f79f-00c04fc2dcd2")

    $RulesToRemove = $Acl.Access | Where-Object {{ $_.IdentityReference.Value -match "{source}" -and $SyncGuids -contains $_.ObjectType }}

    if ($RulesToRemove) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Removed DCSync ACEs." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No DCSync ACEs found for user." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""