# core/remediation/ps_templates.py
"""
PowerShell Remediation Script Templates for ViperACL.
Provides parameterized script snippets covering all 19 accepted Active Directory edge conditions.
"""

HEADER = """<#
.SYNOPSIS
    ViperACL Automated Remediation Script
.DESCRIPTION
    This script was automatically generated by ViperACL (Phase 4 Remediation Engine).
    It applies surgical Access Control List (ACL) and Active Directory mitigations
    to neutralize identified attack paths.
.NOTES
    Generated for Project: {project_name}
    Timestamp: {timestamp}
    Total Mitigations: {action_count}
#>

Import-Module ActiveDirectory -ErrorAction Stop
Set-Location AD:

$ErrorActionPreference = "Continue"
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host " Starting ViperACL Remediation Protocol" -ForegroundColor Cyan
Write-Host " Target Domain Context: {domain}" -ForegroundColor DarkCyan
Write-Host " Total Actions Scheduled: {action_count}" -ForegroundColor DarkCyan
Write-Host "=================================================`n" -ForegroundColor Cyan
"""

FOOTER = """
Write-Host "`n=================================================" -ForegroundColor Cyan
Write-Host " Remediation Protocol Execution Completed." -ForegroundColor Green
Write-Host " Please re-run SharpHound collection to verify path severance." -ForegroundColor Gray
Write-Host "=================================================" -ForegroundColor Cyan
"""

# 1. MemberOf to GROUP
REMOVE_GROUP_MEMBER = """
Write-Host "[*] Action: Remove '{source}' from Group '{target}'"
try {{
    $TargetObj = Get-ADGroup -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -ErrorAction SilentlyContinue
    if (-not $TargetObj) {{ $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" }}
    $SourceObj = Get-ADObject -Filter "Name -eq '{source}' -or SamAccountName -eq '{source}'"
    
    if (-not $TargetObj) {{ throw "Could not resolve target group '{target}' in AD." }}
    if (-not $SourceObj) {{ throw "Could not resolve source member '{source}' in AD." }}

    $CurrentMembers = Get-ADGroupMember -Identity $TargetObj.DistinguishedName -ErrorAction SilentlyContinue
    $IsMember = $CurrentMembers | Where-Object {{ $_.DistinguishedName -eq $SourceObj.DistinguishedName }}

    if ($IsMember) {{
        Remove-ADGroupMember -Identity $TargetObj.DistinguishedName -Members $SourceObj.DistinguishedName -Confirm:$false
        Write-Host "  [+] SUCCESS: Member '{source}' removed from group '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: Member '{source}' is not currently in group '{target}'. No action needed." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 2. DCSync to DOMAIN
REMOVE_DCSYNC = """
Write-Host "[*] Action: Revoke DCSync rights for '{source}' on Domain Root '{target}'"
try {{
    $DomainObj = Get-ADDomain '{target}' -ErrorAction SilentlyContinue
    if (-not $DomainObj) {{ $DomainObj = Get-ADDomain }}
    if (-not $DomainObj) {{ throw "Could not resolve Domain Root '{target}'." }}
    
    $DomainDN = $DomainObj.DistinguishedName
    $Acl = Get-Acl -Path "AD:\\$DomainDN"
    
    # Replication Extended Rights GUIDs:
    # DS-Replication-Get-Changes: 1131f6aa-9c07-11d1-f79f-00c04fc2dcd2
    # DS-Replication-Get-Changes-All: 1131f6ad-9c07-11d1-f79f-00c04fc2dcd2
    # DS-Replication-Get-Changes-In-Filtered-Set: 89e95b76-444d-11d2-f003-00c04fd8d802
    $SyncGuids = @("1131f6aa-9c07-11d1-f79f-00c04fc2dcd2", "1131f6ad-9c07-11d1-f79f-00c04fc2dcd2", "89e95b76-444d-11d2-f003-00c04fd8d802")

    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and (
            $SyncGuids -contains $_.ObjectType -or 
            $_.ActiveDirectoryRights -match "GenericAll|ExtendedRight|AllExtendedRights"
        )
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$DomainDN" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Revoked $($RulesToRemove.Count) DCSync replication ACE(s) for '{source}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No matching DCSync ACEs found for '{source}' on Domain Root." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 3. AddMember to GROUP
REMOVE_ADD_MEMBER = """
Write-Host "[*] Action: Revoke AddMember / Self-Membership rights for '{source}' on Group '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) {{ throw "Could not resolve target group '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    # Member property schema GUID: bf9679c0-0de6-11d0-a285-00aa003049e2
    $MemberAttrGuid = "bf9679c0-0de6-11d0-a285-00aa003049e2"
    
    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and (
            $_.ActiveDirectoryRights -match "WriteProperty" -or
            $_.ActiveDirectoryRights -match "GenericWrite" -or
            $_.ObjectType -eq $MemberAttrGuid
        )
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Revoked AddMember permissions for '{source}' on group '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No matching AddMember ACE found. It may have already been removed." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 4. GenericWrite to GROUP
REMOVE_GENERIC_WRITE_GROUP = """
Write-Host "[*] Action: Revoke GenericWrite rights for '{source}' on Group '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) {{ throw "Could not resolve target group '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and (
            $_.ActiveDirectoryRights -match "GenericWrite|WriteProperty"
        )
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Removed GenericWrite ACE(s) for '{source}' on group '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No GenericWrite ACEs found on group '{target}'." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 5, 6, 7. GenericAll to USER / GROUP / DOMAIN
REMOVE_GENERIC_ALL = """
Write-Host "[*] Action: Revoke GenericAll rights for '{source}' on {target_type} '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj -and "{target_type}" -eq "Domain") {{
        $TargetObj = Get-ADDomain '{target}' -ErrorAction SilentlyContinue
        if (-not $TargetObj) {{ $TargetObj = Get-ADDomain }}
    }}
    if (-not $TargetObj) {{ throw "Could not resolve target {target_type} '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and $_.ActiveDirectoryRights -match "GenericAll"
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Revoked GenericAll ACE(s) for '{source}' on '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No matching GenericAll ACE found for '{source}' on '{target}'." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 8, 9. AllExtendedRights to USER / DOMAIN
REMOVE_ALL_EXTENDED_RIGHTS = """
Write-Host "[*] Action: Revoke AllExtendedRights for '{source}' on {target_type} '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj -and "{target_type}" -eq "Domain") {{
        $TargetObj = Get-ADDomain '{target}' -ErrorAction SilentlyContinue
        if (-not $TargetObj) {{ $TargetObj = Get-ADDomain }}
    }}
    if (-not $TargetObj) {{ throw "Could not resolve target {target_type} '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and (
            $_.ActiveDirectoryRights -match "ExtendedRight|AllExtendedRights"
        )
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Revoked AllExtendedRights ACE(s) for '{source}' on '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No matching AllExtendedRights ACE found on '{target}'." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 10, 11, 12. WriteDacl to USER / GROUP / DOMAIN
REMOVE_WRITE_DACL = """
Write-Host "[*] Action: Revoke WriteDacl rights for '{source}' on {target_type} '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj -and "{target_type}" -eq "Domain") {{
        $TargetObj = Get-ADDomain '{target}' -ErrorAction SilentlyContinue
        if (-not $TargetObj) {{ $TargetObj = Get-ADDomain }}
    }}
    if (-not $TargetObj) {{ throw "Could not resolve target {target_type} '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and $_.ActiveDirectoryRights -match "WriteDacl"
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Revoked WriteDacl ACE(s) for '{source}' on '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No matching WriteDacl ACE found on '{target}'." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 13, 14, 15. Owns to USER / GROUP / DOMAIN
RESET_OWNERSHIP = """
Write-Host "[*] Action: Reset Object Owner of {target_type} '{target}' (Currently Owned by '{source}') to Domain Admins"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj -and "{target_type}" -eq "Domain") {{
        $TargetObj = Get-ADDomain '{target}' -ErrorAction SilentlyContinue
        if (-not $TargetObj) {{ $TargetObj = Get-ADDomain }}
    }}
    if (-not $TargetObj) {{ throw "Could not resolve target {target_type} '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $DomainAdmins = Get-ADGroup -Filter "Name -eq 'Domain Admins' -or SamAccountName -eq 'Domain Admins'" -ErrorAction SilentlyContinue
    $OwnerAccount = if ($DomainAdmins) {{ [System.Security.Principal.NTAccount]$DomainAdmins.SamAccountName }} else {{ [System.Security.Principal.NTAccount]"Domain Admins" }}
    
    $Acl.SetOwner($OwnerAccount)
    Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
    Write-Host "  [+] SUCCESS: Restored ownership of '{target}' to Domain Admins." -ForegroundColor Green
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 16, 17, 18. WriteOwner to USER / GROUP / DOMAIN
REMOVE_WRITE_OWNER = """
Write-Host "[*] Action: Revoke WriteOwner rights for '{source}' on {target_type} '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj -and "{target_type}" -eq "Domain") {{
        $TargetObj = Get-ADDomain '{target}' -ErrorAction SilentlyContinue
        if (-not $TargetObj) {{ $TargetObj = Get-ADDomain }}
    }}
    if (-not $TargetObj) {{ throw "Could not resolve target {target_type} '{target}' in AD." }}
    
    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and $_.ActiveDirectoryRights -match "WriteOwner"
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Revoked WriteOwner ACE(s) for '{source}' on '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No matching WriteOwner ACE found on '{target}'." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""

# 19. ForceChangePassword to USER
REMOVE_FORCE_CHANGE_PASSWORD = """
Write-Host "[*] Action: Revoke ForceChangePassword right for '{source}' on User '{target}'"
try {{
    $TargetObj = Get-ADObject -Filter "Name -eq '{target}' -or SamAccountName -eq '{target}'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) {{ throw "Could not resolve target User '{target}' in AD." }}

    $Acl = Get-Acl -Path "AD:\\$($TargetObj.DistinguishedName)"
    # GUID for User-Force-Change-Password Extended Right
    $ResetPwGuid = "00299570-246d-11d0-a768-00aa006e0529" 
    
    $RulesToRemove = @($Acl.Access | Where-Object {{
        $_.IdentityReference.Value -match "{source}" -and (
            $_.ObjectType -eq $ResetPwGuid -or 
            ($_.ActiveDirectoryRights -match "ExtendedRight" -and $_.ObjectType -eq $ResetPwGuid)
        )
    }})

    if ($RulesToRemove.Count -gt 0) {{
        foreach ($Rule in $RulesToRemove) {{
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }}
        Set-Acl -Path "AD:\\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Stripped ForceChangePassword privilege for '{source}' on '{target}'." -ForegroundColor Green
    }} else {{
        Write-Host "  [~] STATUS: No ForceChangePassword ACE found for '{source}'." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}}
"""