<#
.SYNOPSIS
    ViperACL Automated Remediation Script
.DESCRIPTION
    This script was automatically generated by ViperACL (Phase 4).
    It contains specific mitigation steps to break identified Active Directory attack paths.
#>
Import-Module ActiveDirectory
Set-Location AD:

$ErrorActionPreference = "Stop"
Write-Host "=================================================" -ForegroundColor Cyan
Write-Host " Starting ViperACL Remediation Protocol" -ForegroundColor Cyan
Write-Host "=================================================`n" -ForegroundColor Cyan

# --- Action 1: Mitigate ForceChangePassword ---
Write-Host "[*] Action: Remove 'ForceChangePassword' right for 'WLEY' on 'DAMUNDSEN'"
try {
    $TargetObj = Get-ADObject -Filter "Name -eq 'DAMUNDSEN' -or SamAccountName -eq 'DAMUNDSEN'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) { throw "Could not resolve target 'DAMUNDSEN' in AD." }

    $Acl = Get-Acl -Path "AD:\$($TargetObj.DistinguishedName)"
    # GUID for User-Force-Change-Password Extended Right
    $ResetPwGuid = "00299570-246d-11d0-a768-00aa006e0529" 
    
    $RulesToRemove = $Acl.Access | Where-Object { $_.IdentityReference.Value -match "WLEY" -and $_.ObjectType -eq $ResetPwGuid }

    if ($RulesToRemove) {
        foreach ($Rule in $RulesToRemove) {
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }
        Set-Acl -Path "AD:\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Stripped ForceChangePassword privilege." -ForegroundColor Green
    } else {
        Write-Host "  [~] STATUS: No ForceChangePassword ACE found. It may have already been removed." -ForegroundColor Yellow
    }
} catch {
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

# --- Action 2: Mitigate GenericWrite ---
Write-Host "[*] Action: Remove 'GenericWrite|WriteProperty' right for 'DAMUNDSEN' on 'HELP DESK LEVEL 1'"
try {
    $TargetObj = Get-ADObject -Filter "Name -eq 'HELP DESK LEVEL 1' -or SamAccountName -eq 'HELP DESK LEVEL 1'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) { throw "Could not resolve target 'HELP DESK LEVEL 1' in AD." }
    
    $Acl = Get-Acl -Path "AD:\$($TargetObj.DistinguishedName)"
    $RulesToRemove = $Acl.Access | Where-Object { $_.IdentityReference.Value -match "DAMUNDSEN" -and $_.ActiveDirectoryRights -match "GenericWrite|WriteProperty" }

    if ($RulesToRemove) {
        foreach ($Rule in $RulesToRemove) {
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }
        Set-Acl -Path "AD:\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Removed ACE granting GenericWrite|WriteProperty." -ForegroundColor Green
    } else {
        Write-Host "  [~] STATUS: No matching ACE found. It may have already been removed." -ForegroundColor Yellow
    }
} catch {
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

# --- Action 3: Mitigate MemberOf ---
Write-Host "[*] Action: Remove 'HELP DESK LEVEL 1' from group 'INFORMATION TECHNOLOGY'"
try {
    # Safely resolve Distinguished Names first to prevent null Identity errors
    $TargetObj = Get-ADObject -Filter "Name -eq 'INFORMATION TECHNOLOGY' -or SamAccountName -eq 'INFORMATION TECHNOLOGY'"
    $SourceObj = Get-ADObject -Filter "Name -eq 'HELP DESK LEVEL 1' -or SamAccountName -eq 'HELP DESK LEVEL 1'"
    
    if (-not $TargetObj) { throw "Could not resolve target group 'INFORMATION TECHNOLOGY' in AD." }
    if (-not $SourceObj) { throw "Could not resolve source user 'HELP DESK LEVEL 1' in AD." }

    # Check if the user is actually a member of the group first
    $CurrentMembers = Get-ADGroupMember -Identity $TargetObj.DistinguishedName
    $IsMember = $CurrentMembers | Where-Object { $_.DistinguishedName -eq $SourceObj.DistinguishedName }

    if ($IsMember) {
        Remove-ADGroupMember -Identity $TargetObj.DistinguishedName -Members $SourceObj.DistinguishedName -Confirm:$false
        Write-Host "  [+] SUCCESS: User removed from group." -ForegroundColor Green
    } else {
        Write-Host "  [~] STATUS: User is not currently a member of this group. No action needed." -ForegroundColor Yellow
    }
} catch {
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

# --- Action 4: Mitigate GenericAll ---
Write-Host "[*] Action: Remove 'GenericAll' right for 'INFORMATION TECHNOLOGY' on 'ADUNN'"
try {
    $TargetObj = Get-ADObject -Filter "Name -eq 'ADUNN' -or SamAccountName -eq 'ADUNN'" -IncludeDeletedObjects:$false
    if (-not $TargetObj) { throw "Could not resolve target 'ADUNN' in AD." }
    
    $Acl = Get-Acl -Path "AD:\$($TargetObj.DistinguishedName)"
    $RulesToRemove = $Acl.Access | Where-Object { $_.IdentityReference.Value -match "INFORMATION TECHNOLOGY" -and $_.ActiveDirectoryRights -match "GenericAll" }

    if ($RulesToRemove) {
        foreach ($Rule in $RulesToRemove) {
            $Acl.RemoveAccessRule($Rule) | Out-Null
        }
        Set-Acl -Path "AD:\$($TargetObj.DistinguishedName)" -AclObject $Acl
        Write-Host "  [+] SUCCESS: Removed ACE granting GenericAll." -ForegroundColor Green
    } else {
        Write-Host "  [~] STATUS: No matching ACE found. It may have already been removed." -ForegroundColor Yellow
    }
} catch {
    Write-Host "  [-] FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host "=================================================" -ForegroundColor Cyan
Write-Host " Remediation Protocol Complete." -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Cyan
